'use server';

import { ai } from '@/ai/genkit';
import { z } from 'genkit';
import PDFDocument from 'pdfkit';

const PdfInputSchema = z.object({
  filename: z.string(),
  title: z.string(),
  content: z.string(),
});

/**
 * Compiles a PDF in-memory and returns perfect, uncorrupted Base64.
 * Dynamic layout calculations ensure text wraps without overlapping.
 */
export async function generatePdfInMemory(input: z.infer<typeof PdfInputSchema>) {
  const safeFilename = input.filename.endsWith('.pdf') ? input.filename : `${input.filename}.pdf`;
  const doc = new PDFDocument({ margin: 50, size: 'A4' });
  const chunks: Buffer[] = [];

  doc.on('data', (chunk) => chunks.push(chunk));

  // Draw Theme Background
  doc.rect(0, 0, doc.page.width, doc.page.height).fill('#0d1117');
  
  // Decorative orange top bar
  doc.fillColor('#f0883e').rect(50, 40, doc.page.width - 100, 3).fill();
  
  // 1. Render Title dynamically (calculating wrapping cleanly inside boundaries)
  doc.fillColor('#f0883e')
    .font('Helvetica-Bold')
    .fontSize(20)
    .text(input.title.toUpperCase(), 50, 60, {
      width: doc.page.width - 100
    });

  // 2. Position the subheader relative to the final line of the wrapped title
  const subheaderY = doc.y + 8;
  doc.fillColor('#8b949e')
    .font('Helvetica')
    .fontSize(8)
    .text("AUTO-GENERATED BY JIMSKAY INTELLIGENCE PROTOCOL", 50, subheaderY);

  // 3. Position the content starting Y-coordinate safely below the subheader
  let currentY = doc.y + 30;
  doc.fillColor('#c9d1d9').fontSize(10);

  const paragraphs = input.content.split('\n\n');
  for (const para of paragraphs) {
    const cleanPara = para.trim();
    if (!cleanPara) continue;

    if (currentY > doc.page.height - 100) {
      doc.addPage();
      doc.rect(0, 0, doc.page.width, doc.page.height).fill('#0d1117');
      doc.fillColor('#f0883e').rect(50, 40, doc.page.width - 100, 3).fill();
      currentY = 60;
    }

    if (cleanPara.startsWith('###')) {
      doc.fillColor('#58a6ff').font('Helvetica-Bold').fontSize(12).text(cleanPara.replace('###', '').trim(), 50, currentY);
      currentY += 24;
    } else if (cleanPara.startsWith('*') || cleanPara.startsWith('-')) {
      const items = cleanPara.split('\n');
      doc.fillColor('#c9d1d9').font('Helvetica').fontSize(10);
      for (const item of items) {
        const cleanItem = item.replace(/^[*-\s]+/, '').trim();
        if (!cleanItem) continue;
        doc.text(`• ${cleanItem}`, 65, currentY);
        currentY += 16;
      }
      currentY += 6;
    } else {
      doc.fillColor('#c9d1d9').font('Helvetica').fontSize(10).text(cleanPara, 50, currentY, {
        align: 'justify',
        width: doc.page.width - 100,
        lineGap: 4
      });
      currentY += doc.heightOfString(cleanPara, { width: doc.page.width - 100, lineGap: 4 }) + 16;
    }
  }

  doc.end();

  const pdfBuffer = await new Promise<Buffer>((resolve, reject) => {
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', (err) => reject(err));
  });

  return {
    base64Data: pdfBuffer.toString('base64'),
    filename: safeFilename,
  };
}

// Keep the tool schema registered for Genkit
export const pdfGeneratorTool = ai.defineTool(
  {
    name: 'pdfGeneratorTool',
    description: 'Generates a PDF document in memory.',
    inputSchema: PdfInputSchema,
    outputSchema: z.object({ filename: z.string(), status: z.string() }),
  },
  async (input) => {
    return { filename: input.filename, status: "Staged on server memory" };
  }
);